[package]
name = "test_mvp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.2"
violette = { path = "../../lib/violette" }
violette-derive = { path = "../../lib/violette-derive" }
rose-core = { path = "../../lib/rose-core" }
#rose-ui = { path = "../../lib/rose-ui" }
rose-platform = { path = "../../lib/rose-platform" }

bytemuck.workspace = true
#egui = { workspace = true }
eyre.workspace = true
glam.workspace = true
tracing.workspace = true
