[package]
name = "bone-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rose = { path = "../../lib/rose" }
violette = { path = "../../lib/violette" }