[package]
name = "bone-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rose-core = { path = "../../lib/rose-core" }
rose-platform = { path = "../../lib/rose-platform" }
rose-renderer = { path = "../../lib/rose-renderer" }
violette = { path = "../../lib/violette" }

eyre.workspace = true
glam.workspace = true