[package]
name = "hello_triangle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rose-core = { path = "../../lib/rose-core" }
rose-platform = { path = "../../lib/rose-platform", features = ["ui"] }
rose-ui = { path = "../../lib/rose-ui" }

eyre.workspace = true