[package]
name = "sandbox-bevy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.9.1", default-features = false, features = ["bevy_asset", "bevy_winit", "trace", "bevy_dylib"] }
color-eyre = "0.6.2"
csv = "1.2.0"
dolly = "0.4.0"
glutin = "0.30.3"
glutin-winit = "0.2.1"
rand = "0.8.5"
tracing-subscriber = "0.3.16"

pan-orbit-camera = { path = "../../lib/pan-orbit-camera" }
rose-core = { path = "../../lib/rose-core" }
rose-platform = { path = "../../lib/rose-platform", features = ["ui"] }
rose-renderer = { path = "../../lib/rose-renderer", features = ["debug-ui"] }
rose-ui = { path = "../../lib/rose-ui" }
violette = { path = "../../lib/violette" }

bytemuck.workspace = true
egui.workspace = true
eyre.workspace = true
glam = { workspace = true, features = ["serde", "rand"] }
tracing.workspace = true
winit.workspace = true
once_cell = "1.17.1"

[features]
tracy = ["rose-platform/tracy"]
