[package]
name = "transform_hierarchy"
edition.workspace = true
version.workspace = true
authors.workspace = true
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rose = { path = "../../lib/rose" }

eyre.workspace = true